<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><UseWPF>true</UseWPF></PropertyGroup><ItemGroup><ProjectReference Include="..\Core\Core.csproj"/><ProjectReference Include="..\Rt\Rt.csproj"/><Compile Include="..\Viewer\ReformatContours.cs" Link="ReformatContours.cs"/><Compile Include="..\Viewer\RenderScene.cs" Link="RenderScene.cs"/><Compile Include="..\Viewer\FieldArrangementDrawing.cs" Link="FieldArrangementDrawing.cs"/><Compile Include="..\Viewer\SlicePane.cs" Link="SlicePane.cs"/></ItemGroup></Project>
