<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><UseWPF>true</UseWPF><AssemblyName>QuickLook.DicomRT.Viewer</AssemblyName></PropertyGroup><ItemGroup><Reference Include="System.Windows.Forms" /><ProjectReference Include="..\Core\Core.csproj" /><ProjectReference Include="..\Rt\Rt.csproj" /><Resource Include="..\assets\dicom-rt.png" Link="Assets\dicom-rt.png" /><Resource Include="..\assets\dicom-rt.ico" Link="Assets\dicom-rt.ico" /></ItemGroup><ItemGroup>
  <PackageReference Include="HelixToolkit.Wpf.SharpDX" Version="2.27.3" />
</ItemGroup></Project>
